task1
electron01/MJC-School pull request #1
Opened 2021-03-27 13:28 UTC by electron01

Git and Build tools

2021-03-27 14:20 UTC, AliakseiBrui requested changes

2021-03-27 14:20 UTC, AliakseiBrui commented on stage #3/java/module #1. GIT & Build Tools/build tools/task2/multiProject/local.properties
> +## This file must *NOT* be checked into Version Control Systems,
этого файла не должно быть в гите

2021-03-27 14:20 UTC, AliakseiBrui commented on stage #3/java/module #1. GIT & Build Tools/build tools/task2/utils/build.gradle
> +
лишняя строка

2021-03-27 14:20 UTC, AliakseiBrui commented on stage #3/java/module #1. GIT & Build Tools/build tools/task2/utils/build.gradle
> +
тут тоже лишние строки

2021-03-27 14:20 UTC, AliakseiBrui commented on stage #3/java/module #1. GIT & Build Tools/build tools/task2/utils/src/main/java/by/tkachuk/utils/StringUtils.java
> +        if (!isNumbers(str)) {
используй !NumberUtils.isCreatable(str) вместо этого

2021-03-27 14:20 UTC, AliakseiBrui commented on stage #3/java/module #1. GIT & Build Tools/build tools/task2/utils/src/main/java/by/tkachuk/utils/StringUtils.java
> +
лишние строки

2021-03-27 14:20 UTC, AliakseiBrui commented on stage #3/java/module #1. GIT & Build Tools/build tools/task2/utils/src/test/java/by/tkachuk/utils/StringUtilsTest.java
> +    @Test()
скобки здесь не нужны

2021-03-27 14:20 UTC, AliakseiBrui commented on stage #3/java/module #1. GIT & Build Tools/build tools/task2/multiProject/core/src/main/java/by/tkachuk/core/Utils.java
> +
лишние строки

2021-03-27 14:20 UTC, AliakseiBrui commented on stage #3/java/module #1. GIT & Build Tools/build tools/task2/multiProject/core/src/main/java/by/tkachuk/core/Utils.java
> +        return Arrays.stream(str).allMatch(s -> StringUtils.isPositiveNumber(s));
здесь можно написать через method reference: Arrays.stream(str).allMatch(StringUtils::isPositiveNumber);

2021-03-27 14:20 UTC, AliakseiBrui commented on stage #3/java/module #1. GIT & Build Tools/build tools/task2/utils/src/test/java/by/tkachuk/utils/StringUtilsTest.java
> +
лишние строки

2021-03-27 15:27 UTC, electron01 commented on stage #3/java/module #1. GIT & Build Tools/build tools/task2/utils/src/main/java/by/tkachuk/utils/StringUtils.java
> +        if (!isNumbers(str)) {
Окей, просто, на сколько я понял, этот метод проверяет корректность чисел, не только в десятичной системе,
но и в двоичной системе, и в шестнадцатеричной системе, а тут, если я не ошибаюсь, логика определения положительного / отрицательного числа, другая, поэтому я решил написать свой метод, только для работы с десятичной системы
Хорошо, я изменю

2021-03-28 07:21 UTC, AliakseiBrui requested changes

2021-03-28 07:21 UTC, AliakseiBrui commented on stage #3/java/module #1. GIT & Build Tools/build tools/task2/multiProject/core/src/main/java/by/tkachuk/core/Utils.java
> +public class Utils {
javadoc для класса и метода

2021-03-28 14:40 UTC, AliakseiBrui approved these changes

2021-03-28 14:40 UTC, merged