Module 2
electron01/MJC-School pull request #2
Opened 2021-04-16 01:08 UTC by electron01

Task02

2021-04-16 10:08 UTC, AliakseiBrui requested changes

2021-04-16 10:08 UTC, AliakseiBrui commented on stage #3/java/module #2. REST API Basics/task02/repository/src/main/java/by/epam/esm/dao/CertificateSqlQuery.java
> +public class CertificateSqlQuery {
please divide this on interface and implementation and consider using more descriptive name (i.e. CertificateSqlQueryAssembler)

2021-04-16 10:08 UTC, AliakseiBrui commented on stage #3/java/module #2. REST API Basics/task02/repository/src/main/java/by/epam/esm/dao/CertificateSqlQuery.java
> +
please remove all excessive lines at the end of classes and methods

2021-04-16 10:08 UTC, AliakseiBrui commented on stage #3/java/module #2. REST API Basics/task02/repository/src/main/java/by/epam/esm/dao/CrdTagDao.java
> +    Optional<Tag> getTagByName(String tagName);
use 1 search method name convention (either find or get)

2021-04-16 10:08 UTC, AliakseiBrui commented on stage #3/java/module #2. REST API Basics/task02/repository/src/main/java/by/epam/esm/dao/impl/GiftCertificateDaoImpl.java
> +        CertificateSqlQuery certificateSqlQuery = new CertificateSqlQuery();
better to inject this as a field rather than create a new query builder on each method call

2021-04-16 10:08 UTC, AliakseiBrui commented on stage #3/java/module #2. REST API Basics/task02/repository/src/test/java/by/epam/esm/dao/TestGiftCertificateDao.java
> +    public void getAllCertificateTest() {
please use given-when-then comments in tests

2021-04-16 10:08 UTC, AliakseiBrui commented on stage #3/java/module #2. REST API Basics/task02/service/src/main/java/by/epam/esm/dto/entity/TagDto.java
> +    //@NotBlank(message = "Tag Name can't be empty")
what is this?

2021-04-16 10:08 UTC, AliakseiBrui commented on stage #3/java/module #2. REST API Basics/task02/service/src/main/java/by/epam/esm/service/GiftCertificateService.java
> +    GiftCertificateDto partUpdate(GiftCertificateDto giftCertificateDto);
formatting and javadocs

2021-04-16 10:08 UTC, AliakseiBrui commented on stage #3/java/module #2. REST API Basics/task02/service/src/main/java/by/epam/esm/service/TagService.java
> +    TagDto getByName(String name);
formatting and javadocs

2021-04-16 10:08 UTC, AliakseiBrui commented on stage #3/java/module #2. REST API Basics/task02/service/src/main/java/by/epam/esm/validator/BaseValidator.java
> +public class BaseValidator {
javadocs on class and public methods

2021-04-16 10:08 UTC, AliakseiBrui commented on stage #3/java/module #2. REST API Basics/task02/web/src/main/java/by/epam/esm/controller/GiftCertificateController.java
> +public class GiftCertificateController {
javadocs on class and public methods

2021-04-16 10:08 UTC, AliakseiBrui commented on stage #3/java/module #2. REST API Basics/task02/web/src/main/java/by/epam/esm/controller/TagController.java
> +public class TagController {
javadocs on class and public methods

2021-04-16 10:08 UTC, AliakseiBrui commented on stage #3/java/module #2. REST API Basics/task02/repository/src/main/java/by/epam/esm/dao/BaseDao.java
> +
formatting and javadocs

2021-04-16 10:08 UTC, AliakseiBrui commented on stage #3/java/module #2. REST API Basics/task02/repository/src/main/java/by/epam/esm/dao/CertificateSqlQuery.java
> +public class CertificateSqlQuery {
also javadocs on interface and its methods

2021-04-16 10:08 UTC, AliakseiBrui commented on stage #3/java/module #2. REST API Basics/task02/repository/src/main/java/by/epam/esm/dao/CrdTagDao.java
> +public interface CrdTagDao extends BaseDao<Tag, Integer> {
javadocs

2021-04-16 10:08 UTC, AliakseiBrui commented on stage #3/java/module #2. REST API Basics/task02/repository/src/main/java/by/epam/esm/dao/CrudGiftCertificateDao.java
> +
formatting and javadocs

2021-04-16 10:08 UTC, AliakseiBrui commented on stage #3/java/module #2. REST API Basics/task02/repository/src/main/java/by/epam/esm/enity/GiftCertificate.java
> +public class GiftCertificate extends Entity {
javadoc

2021-04-16 10:08 UTC, AliakseiBrui commented on stage #3/java/module #2. REST API Basics/task02/repository/src/main/java/by/epam/esm/enity/Entity.java
> +public abstract class Entity implements Serializable {
javadoc

2021-04-16 10:08 UTC, AliakseiBrui commented on stage #3/java/module #2. REST API Basics/task02/repository/src/main/java/by/epam/esm/enity/Pagination.java
> +public class Pagination {
javadoc

2021-04-16 10:08 UTC, AliakseiBrui commented on stage #3/java/module #2. REST API Basics/task02/repository/src/main/java/by/epam/esm/enity/Tag.java
> +public class Tag extends Entity {
javadoc

2021-04-16 10:08 UTC, AliakseiBrui commented on stage #3/java/module #2. REST API Basics/task02/repository/src/main/java/by/epam/esm/enity/request/EntityRequestParam.java
> +public interface EntityRequestParam {
javadoc

2021-04-16 10:08 UTC, AliakseiBrui commented on stage #3/java/module #2. REST API Basics/task02/repository/src/main/java/by/epam/esm/enity/request/GiftCertificateRequestParam.java
> +public class GiftCertificateRequestParam implements EntityRequestParam {
javadoc

2021-04-16 10:08 UTC, AliakseiBrui commented on stage #3/java/module #2. REST API Basics/task02/service/src/main/java/by/epam/esm/dto/entity/EntityDto.java
> +public abstract class EntityDto implements Serializable {
javadoc

2021-04-16 10:08 UTC, AliakseiBrui commented on stage #3/java/module #2. REST API Basics/task02/service/src/main/java/by/epam/esm/dto/entity/GiftCertificateDto.java
> +public class GiftCertificateDto extends EntityDto {
javadoc

2021-04-16 10:08 UTC, AliakseiBrui commented on stage #3/java/module #2. REST API Basics/task02/service/src/main/java/by/epam/esm/dto/entity/PaginationDto.java
> +public class PaginationDto {
javadoc

2021-04-16 10:08 UTC, AliakseiBrui commented on stage #3/java/module #2. REST API Basics/task02/service/src/main/java/by/epam/esm/dto/entity/TagDto.java
> +public class TagDto extends EntityDto {
javadoc

2021-04-16 10:08 UTC, AliakseiBrui commented on stage #3/java/module #2. REST API Basics/task02/service/src/main/java/by/epam/esm/dto/entity/request/DtoEntityRequestParam.java
> +public interface DtoEntityRequestParam {
javadoc

2021-04-16 10:08 UTC, AliakseiBrui commented on stage #3/java/module #2. REST API Basics/task02/service/src/main/java/by/epam/esm/dto/entity/request/DtoGiftCertificateRequestParam.java
> +public class DtoGiftCertificateRequestParam implements DtoEntityRequestParam {
javadoc

2021-04-16 10:08 UTC, AliakseiBrui commented on stage #3/java/module #2. REST API Basics/task02/service/src/main/java/by/epam/esm/dto/mapper/GiftCertificateMapper.java
> +public interface GiftCertificateMapper {
javadoc

2021-04-16 10:08 UTC, AliakseiBrui commented on stage #3/java/module #2. REST API Basics/task02/service/src/main/java/by/epam/esm/dto/mapper/GiftCertificateRequestMapper.java
> +public interface GiftCertificateRequestMapper {
javadoc

2021-04-16 10:08 UTC, AliakseiBrui commented on stage #3/java/module #2. REST API Basics/task02/service/src/main/java/by/epam/esm/dto/mapper/PaginationMapper.java
> +public interface PaginationMapper {
javadoc

2021-04-19 06:53 UTC, AliakseiBrui requested changes

2021-04-19 06:53 UTC, AliakseiBrui commented on stage #3/java/module #2. REST API Basics/task02/repository/src/main/java/by/epam/esm/dao/CertificateSqlQueryAssembler.java
> +public class CertificateSqlQueryAssembler implements BaseSqlQueryAssembler {
move public methods of this class to interface and ovveride them here

2021-04-19 07:09 UTC, AliakseiBrui commented on stage #3/java/module #2. REST API Basics/task02/repository/src/main/java/by/epam/esm/dao/impl/GiftCertificateDaoImpl.java
> +    private CertificateSqlQueryAssembler certificateSqlQueryAssembler = new CertificateSqlQueryAssembler();
make this class a @Component and inject interface here using @Autowired

2021-04-20 10:10 UTC, Kiryacheldik commented on stage #3/java/module #2. REST API Basics/task02/repository/src/main/java/by/epam/esm/config/RepoConfig.java
> +    @Value("#{environment['spring.profiles.active'] == 'production' ? ${db.production} : ${db.development}}")
What if in the future another profiles will be added? Bad for extending I think

2021-04-20 10:10 UTC, Kiryacheldik commented on stage #3/java/module #2. REST API Basics/task02/repository/src/main/java/by/epam/esm/config/RepoConfig.java
> +    @Bean(destroyMethod = "close")//optional
Need this comment?

2021-04-20 10:11 UTC, Kiryacheldik commented on stage #3/java/module #2. REST API Basics/task02/repository/src/main/java/by/epam/esm/config/RepoConfig.java
> +    @Bean(destroyMethod = "close")//optional
Need destroyMethod flat?

2021-04-20 10:12 UTC, Kiryacheldik commented on stage #3/java/module #2. REST API Basics/task02/repository/src/main/java/by/epam/esm/dao/CertificateSqlQueryAssembler.java
> +    CertificateSqlQueryAssemblerImpl.SqlQuery createPartUpdateRequest (GiftCertificate certificate);
Format code please

2021-04-20 10:13 UTC, Kiryacheldik commented on stage #3/java/module #2. REST API Basics/task02/repository/src/main/java/by/epam/esm/dao/CertificateSqlQueryAssembler.java
> +public interface CertificateSqlQueryAssembler {
Why Assembler?

2021-04-20 10:14 UTC, Kiryacheldik commented on stage #3/java/module #2. REST API Basics/task02/repository/src/main/java/by/epam/esm/dao/CertificateSqlQueryAssemblerImpl.java
> +    private boolean checkingForEmptyString(String str) {
checkFor...

2021-04-20 10:15 UTC, Kiryacheldik commented on stage #3/java/module #2. REST API Basics/task02/repository/src/main/java/by/epam/esm/dao/CertificateSqlQueryAssemblerImpl.java
> +    public static class SqlQuery {
What is an advantage to have this inner class? Why don't to move it outside?

2021-04-20 10:17 UTC, Kiryacheldik commented on stage #3/java/module #2. REST API Basics/task02/repository/src/main/java/by/epam/esm/dao/CrudGiftCertificateDao.java
> +    GiftCertificate partUpdate(GiftCertificate entity);
Why do you create separate method for part Update? Update is update, it doesn't matter if it is patch or put method, you are updating entity and you should you one dao method for that.

2021-04-20 10:20 UTC, Kiryacheldik commented on stage #3/java/module #2. REST API Basics/task02/repository/src/main/java/by/epam/esm/dao/impl/GiftCertificateDaoImpl.java
> +    private void addToTagGiftCertificate(GiftCertificate giftCertificate) {
addTagToCertificate would be better I suppose

2021-04-20 10:22 UTC, Kiryacheldik commented on stage #3/java/module #2. REST API Basics/task02/repository/src/main/java/by/epam/esm/dao/impl/TagDaoImpl.java
> +    private static final String FIND_ALL_REQUEST = "SELECT tag_id, name FROM tag WHERE remove=FALSE LIMIT ?, ?";
Not sure these sql queries should be here, you can create separate class for them

2021-04-20 10:23 UTC, Kiryacheldik commented on stage #3/java/module #2. REST API Basics/task02/repository/src/main/java/by/epam/esm/enity/Entity.java
> +public abstract class Entity implements Serializable {
Please explain me the purpose of Serializable interface here, how does it help you in your current app?

2021-04-20 10:23 UTC, Kiryacheldik commented on stage #3/java/module #2. REST API Basics/task02/repository/src/main/java/by/epam/esm/enity/Entity.java
> +    private Integer id;
long

2021-04-20 10:26 UTC, Kiryacheldik commented on stage #3/java/module #2. REST API Basics/task02/repository/src/test/java/by/epam/esm/RepositoryConfig.java
> +    @Autowired
So, Are you sure you need to autowire beans and then create them through @Bean annotation?
You use both @Component and @Bean approaches, please read more about how it works

2021-04-20 10:28 UTC, Kiryacheldik commented on stage #3/java/module #2. REST API Basics/task02/repository/src/test/resources/DBScript.sql
> +INSERT INTO gift_certificate (name,description,price,duration,create_date,last_update_date) VALUES
That's good) You have Script for creation the schema of your DB. Do you think anyone needs your fake data?

2021-04-20 10:30 UTC, Kiryacheldik commented on stage #3/java/module #2. REST API Basics/task02/service/src/main/java/by/epam/esm/dto/entity/GiftCertificateDto.java
> +    @Pattern(regexp = "(?=.*([a-zA-Z\\.]\\s*){3,})(?=(^[\\s\\S]{0,25}$)).*",
Are you sure you need such sctrict validation for name of certificate?

2021-04-20 10:30 UTC, Kiryacheldik commented on stage #3/java/module #2. REST API Basics/task02/service/src/main/java/by/epam/esm/dto/entity/GiftCertificateDto.java
> +    public String toString() {
Where are you using toString method?

2021-04-20 10:30 UTC, Kiryacheldik commented on stage #3/java/module #2. REST API Basics/task02/service/src/main/java/by/epam/esm/dto/entity/GiftCertificateDto.java
> +    public String toString() {
In your app

2021-04-20 10:32 UTC, Kiryacheldik commented on stage #3/java/module #2. REST API Basics/task02/service/src/main/java/by/epam/esm/service/GiftCertificateService.java
> +public interface GiftCertificateService extends BaseService<GiftCertificateDto,Integer> {
long

2021-04-20 10:33 UTC, Kiryacheldik commented on stage #3/java/module #2. REST API Basics/task02/service/src/main/java/by/epam/esm/service/impl/GiftCertificateServiceImpl.java
> +    public GiftCertificateDto add(GiftCertificateDto dto) {
add or save? in one place you have save(), in another add(), please follow the same naming strategy

2021-04-20 10:34 UTC, Kiryacheldik commented on stage #3/java/module #2. REST API Basics/task02/service/src/main/java/by/epam/esm/service/impl/GiftCertificateServiceImpl.java
> +        checkIsGiftCertificateNameExists(dto);
checkIf....

2021-04-20 10:35 UTC, Kiryacheldik commented on stage #3/java/module #2. REST API Basics/task02/service/src/main/java/by/epam/esm/service/impl/GiftCertificateServiceImpl.java
> +        GiftCertificate newGiftCertificate = giftCertificateMapper.giftCertificateDtoToGiftCertificate(dto);
Why can't you name just toEntity(Dto dto) method?

2021-04-20 10:38 UTC, Kiryacheldik commented on stage #3/java/module #2. REST API Basics/task02/service/src/main/java/by/epam/esm/service/impl/GiftCertificateServiceImpl.java
> +                    .filter(tagDto -> tagDto.getName() != null)
Sooo, do you think that there cannot be tags with just 'id' or just 'name'? Also there is a requirement:
If tag doesn't exist, it must be created

2021-04-20 10:38 UTC, Kiryacheldik commented on stage #3/java/module #2. REST API Basics/task02/service/src/main/java/by/epam/esm/service/impl/GiftCertificateServiceImpl.java
> +    public GiftCertificateDto update(GiftCertificateDto giftCertificateDto) {
I don't see any transactions

2021-04-20 10:39 UTC, Kiryacheldik commented on stage #3/java/module #2. REST API Basics/task02/service/src/main/java/by/epam/esm/validator/BaseValidator.java
> +        boolean isUnCorrectDto = false;
incorrect

2021-04-20 10:40 UTC, Kiryacheldik commented on stage #3/java/module #2. REST API Basics/task02/service/src/main/java/by/epam/esm/validator/BaseValidator.java
> +        if (!(atLeastOneNonNullParameter(dto))) {
I'm not sure the reflection is the best approach, try another way please

2021-04-20 10:42 UTC, Kiryacheldik commented on stage #3/java/module #2. REST API Basics/task02/service/src/test/java/by/epam/esm/ServiceConfig.java
> +    private BaseValidator validator;
Please read about how AnnotationConfigAppContext works

2021-04-20 10:43 UTC, Kiryacheldik commented on stage #3/java/module #2. REST API Basics/task02/web/src/main/java/by/epam/esm/controller/GiftCertificateController.java
> +    public GiftCertificateDto updatePartOfCertificate(@PathVariable Integer id, @RequestBody GiftCertificateDto giftCertificateDto) {
204 should be if I'm not wrong

2021-04-20 10:43 UTC, Kiryacheldik commented on stage #3/java/module #2. REST API Basics/task02/web/src/main/java/by/epam/esm/controller/GiftCertificateController.java
> +    public GiftCertificateDto updateGiftCertificate(@RequestBody GiftCertificateDto giftCertificateDto, @PathVariable Integer id) {
What status code?

2021-04-20 10:43 UTC, Kiryacheldik commented on stage #3/java/module #2. REST API Basics/task02/web/src/main/java/by/epam/esm/controller/GiftCertificateController.java
> +        return giftCertificateService.add(giftCertificateDto);
Consider the using of ResponseEntity

2021-04-20 10:45 UTC, Kiryacheldik commented on stage #3/java/module #2. REST API Basics/task02/web/src/main/java/by/epam/esm/controller/TagController.java
> +    @PutMapping("/{id}")
Requirement for tags was CRD operations, why have added put and patch?

2021-04-27 20:39 UTC, AliakseiBrui approved these changes

2021-04-28 06:45 UTC, Kiryacheldik approved these changes

2021-04-28 06:47 UTC, merged